function Pointsreferences = importPointsReferences(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  POINTSREFERENCES = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  POINTSREFERENCES = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  POINTSREFERENCES = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Pointsreferences = importfile("C:\autonomous-vehicle\vehicle-pure-pursuit\Models\04_Arrieta\Points-references.xlsx", "Hoja1", [1, 51]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Sep-2020 14:52:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 51];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
Pointsreferences = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Pointsreferences = [Pointsreferences; tb]; %#ok<AGROW>
end

%% Convert to output type
Pointsreferences = table2array(Pointsreferences);
end