function egoActor = packEgo(pos,vel,yaw,yawRate)
% Pack ego information into a single ego actor bus
%
% Imoprtant note:
% Output is a bus of type BusActorsActors. This is the same bus used by the
% Scenario Reader to output an individual actor. If you change the
% output bus name of Scenario Reader, change the output bus name here
% as well by clicking on 'Edit Data' in the menu above.

egoActor = struct(...
    'ActorID',67,...
    'Position', [pos(1) pos(2) 0], ...
    'Velocity', [vel(1) vel(2) 0], ...
    'Roll', 0, ...
    'Pitch', 0, ...
    'Yaw', yaw, ...
    'AngularVelocity', [0 0 yawRate]);

end